# Generated by Django 5.0 on 2023-12-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accuracy_Phishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('Accuracy_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Accuracy_SQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('Accuracy_percentage', models.FloatField()),
            ],
        ),
    ]
